version: "3.3"

services:
  db:
    container_name: mysql_quiz
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quiz

  adminer:
    container_name: adminer_quiz
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
  nginx:
    container_name: nginx_quiz
    build: images/nginx
    command: nginx -g "daemon off;"
    volumes:
      - ./quiz:/var/www/html
    links:
      - php
    ports:
      - "80:80"
    depends_on:
      - db

  php:
    container_name: php_quiz
    build: images/php
    volumes:
      - ./quiz:/var/www/html
    working_dir: /var/www/html
    command: php-fpm
    links:
      - db:db
    ports:
      - "9000:9000"
    depends_on:
      - db
#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local